namespace Celcat.Verto.DataStore.Common.Entities
{
    // taken from Ct7 codebase (CTDataDLL...ctEntityType.h)
    public enum Ct7Entity
    {
        Course = 600,
        Module,
        Group,
        Staff,
        Room,
        Student,
        Equipment,
        Team,
        Terminology,
        Faculty,
        Department,
        Fixture,
        Layout,
        Site,
        Span,
        Role,
        Origin,
        Event,
        EventCat,
        User,
        WeekScheme,
        Charge,
        Exam,
        Session,
        Slot,
        Supervisor,
        ExamSet,
        Constraint,
        Template,
        TemplateStaffEntry,
        TemplateRoomEntry,
        ConstraintDef,
        ConstraintGenre,
        GroupSplit,
        EventStore,
        DefaultAccessRights,
        MultiSelect,
        StaffCat,
        Mark,
        AuxMark,
        Undefined
    }
}
